# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_pagetext_text_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetext',
            name='text_html',
            field=models.TextField(blank=True),
        ),
    ]
